lesson23/final_project/final/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('auth/', include(('users.urls', 'users'), namespace='users')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
]

# Зададим правильное отображение медиа контента в режиме отладки.
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

# Укажем пользовательский обработчик ошибки 404 как основной
handler404 = 'core.views.page_not_found'

lesson23/final_project/posts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path(
        'post_detail/<int:pk>/',
        views.PostDetailView.as_view(),
        name='post_detail'
    ),
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('post_add/', views.PostAddView.as_view(), name='post_add'),
]

lesson23/final_project/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
]

lesson23/final_project/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .validators import validate_long_value

User = get_user_model()


class Post(models.Model):
    '''Модель публикации.'''
    title = models.CharField(max_length=255)
    # Функции-валидаторы передаются именованным аргументом в виде списка.
    text = models.TextField(validators=[validate_long_value])
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='posts'
    )
    pub_date = models.DateTimeField(auto_now_add=True)
    is_visible = models.BooleanField(default=True)
    # Поле модели для хранения изображений
    # Атрибут upload_to определяет, где конкретно в папке media/
    # будут сохраняться изображения.
    image = models.ImageField(
        blank=True,
        upload_to='posts/',
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

    def __str__(self):
        return self.title[:20]

lesson23/final_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    '''Кастомная модель пользователя.'''
    birth_year = models.DateField(
        verbose_name='Год рождения',
        blank=False,
        null=True,
    )

    class Meta:
        ordering = ['birth_year']
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username[:20]

lesson23/final_project/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

User = get_user_model()


# Форма регистрации пользователя, наследуется от встроенной.
class MyUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'birth_year']

    # Валидатор-метод для отдельного поля
    # Проверяет, есть ли в имени (поле first_name) слово 'Руслан'.
    # В этом случае поднимается ошибка.
    def clean_first_name(self):
        data = self.cleaned_data['first_name']
        if 'Руслан' in data:
            raise forms.ValidationError('Руслану регистрация запрещена!')
        return data

lesson23/final_project/core/views.py
from django.shortcuts import render


# Представление для пользовательской ошибки 404
def page_not_found(request, exception):
    return render(
        request,
        'core/404.html',
        {'path': request.path},
        status=404
    )

lesson23/final_project/posts/views.py
from django.views.generic import ListView, DetailView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Post


class PostListView(ListView):
    '''Представление на основе класса для получения списка публикаций.'''
    queryset = Post.objects.filter(is_visible=True)
    paginate_by = 4
    template_name = 'posts/post_list.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):
    '''Представление на основе класса для получения отдельной публикации.'''
    model = Post
    context_object_name = 'post'
    template_name = 'posts/post_detail.html'


class PostAddView(LoginRequiredMixin, CreateView):
    '''Представление на основе класса для добавления новой публикации.'''
    model = Post
    template_name = 'posts/post_form.html'
    success_url = reverse_lazy('posts:post_list')
    fields = ['title', 'text', 'image']

    def form_valid(self, form):
        # Зададим создаваемым публикациям в качестве автора
        # авторизированного пользователя.
        # Подобные действия можно осуществить через определение
        # метода form_valid(), вызываемого после успешной проверки формы.

        # Явно обозначаем, что публикацию с данными из формы (в виде объекта)
        # сохранять в базу данных пока не надо.
        instance = form.save(commit=False)

        # Задаем данной публикации авторизированного пользователя как автора.
        instance.author = self.request.user

        # После этого сохраняем дополненный объект в БД.
        instance.save()

        # При успешном сохранении перенаправляем пользователя
        # на страницу со списком публикаций.
        return redirect(reverse_lazy('posts:post_list'))


# Ниже пример приведен для сравнения.
# Считываем данные из формы посредством представления на основе функции (FBV).
# Автор задается публикации только после получения данных из формы.
# @login_required
# def add_post(request):
#     form = PostForm(request.POST)
#     if form.is_valid():
#         post = form.save(commit=False)
#         post.author = request.user
#         post.save()

lesson23/final_project/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import MyUserForm


# CBV для регистрации пользователя.
class RegisterView(CreateView):
    '''Представление на основе класса для регистрации пользователя.'''
    # Класс формы
    form_class = MyUserForm
    # Явно указаны путь и название используемого шаблона.
    template_name = 'users/register.html'
    # Адрес, куда будет переброшен пользователь после успешной авторизации.
    success_url = reverse_lazy('users:login')

lesson23/final_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Базовый{% endblock %}</title>
</head>
<body>
    <header>
        {% comment %}
            Проходит проверка, авторизирован ли пользователь.
            Авторизированным пользователям отображается кнопка выхода.
            Неавторизированным кнопки регистрации и входа.
        {% endcomment %}
        {% if user.is_authenticated %}
            <div>
                Пользователь {{ user.username }}
            </div>
            <form action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="Выйти">
            </form>
        {% else %}
            <a href="{% url 'users:register' %}">Регистрация</a>
            <a href="{% url 'users:login' %}">Войти</a>
        {% endif %}
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer></footer>
</body>
</html>

lesson23/final_project/templates/index.html
{% extends "base.html" %}

{% block title %}Главная{% endblock title %}
{% block content %}
    <h1>Главная страница</h1>
{% endblock content %}

lesson23/final_project/templates/posts/post_detail.html
{% extends "base.html" %}

{% block title %}Отдельная публикация{% endblock title %}
{% block content %}
    <div>
        <p>{{ post.title }}</p>
        <p>{{ post.text }}</p>
        <p>Автор {{ post.author.username }}</p>
        <p>{{ post.pub_date }}</p>
        {% comment %} Отображение изображения публикации {% endcomment %}
        <p><img src={{ post.image.url }} alt=""></p>
    </div>
{% endblock content %}

lesson23/final_project/templates/posts/post_form.html
{% extends "base.html" %}

{% block title %}Добавление публикации{% endblock title %}
{% block content %}
    <form action="{% url 'posts:post_add' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class='form_field'>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        {% for error in form.errors %}
            <p>{{ error }}</p>
        {% endfor %}
        <input type="submit" value="Опубликовать">
    </form>
{% endblock content %}

lesson23/final_project/templates/posts/post_list.html
{% extends "base.html" %}

{% block title %}Список публикаций{% endblock title %}
{% block content %}
    {% for post in posts %}
        <div>
            {{ post.title }}
            {{ post.text }}
        </div>
    {% endfor %}
{% endblock content %}

lesson23/final_project/templates/users/login.html
{% extends "base.html" %}

{% block title %}Авторизация{% endblock title %}
{% block content %}
    <h1>Авторизация пользователя</h1>
    <form method='post'>
        {% csrf_token %}
        <input type="text" name="username">
        <input type="password" name="password">
        <input type="submit" value="Авторизироваться">
    </form>
{% endblock content %}

lesson23/final_project/templates/users/register.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock title %}
{% block content %}
    <h1>Регистрация пользователя</h1>
    <form method='post'>
        {% csrf_token %}
        {% for field in form %}
            <div class='form_field'>
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        {% comment %} Вывод ошибок, возникающих при валидации {% endcomment %}
        {% if form.errors%}
            {% for field in form %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            {% endfor %}
        {% endif %}
        <input type="submit" value="Зарегистрироваться">
    </form>
{% endblock content %}