lesson22/my_edu_project/my_edu/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts'))
]

lesson22/my_edu_project/posts/urls.py
# Использование представлений от классов, CBV, для обработки адресов.
from django.views.generic import TemplateView
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Использование представления на основе функции, FBV.
    # path('post_form/<int:pk>', views.post_form),

    # Использование представления на основе класса, CBV.
    # path('post_detail/<int:pk>', views.PostView.as_view()),

    # CBV может принимать именованные аргументы для переназначения свойств.
    # Это создает возможность получать разный функционал у одного CBV.
    # path('post_detail2/<int:pk>', views.PostView.as_view(
    #     template_name='user_form.html',
    #     form_class='SecondForm',
    # )),

    # Если необходимо отрисовать шаблон без передачи данных в форме контекста,
    # удобнее использовать встроенный класс TemplateView.
    path('contacts/', TemplateView.as_view(
        template_name='posts/contacts.html')),

    # Можем воспользоваться CBV на основе встроенного класса TemplateView.
    # В нашем случае результат будет тот же, что и в примере выше.
    # path('contacts/', views.ContactsView.as_view()),

    # Применим представление на основе встроенного класса ListView.
    path('posts_list/', views.PostList2View.as_view(), name='post_list'),
]

lesson22/my_edu_project/posts/models.py
from django.db import models


# Простая модель для демонстрации работы CBV.
class Post(models.Model):
    title = models.CharField(max_length=255)
    text = models.TextField()


# Для добавления записей без применения админки сайта
# вызовем в терминале оболочку Django (shell).
# python manage.py shell

# Сначала импортируем модель Post.
# from posts.models import Post
# Далее создаем нужное количество записей командой create.
# Post.objects.create(title='Заголовок', text='Текст')

lesson22/my_edu_project/posts/views.py
# CBV, Class Based Views, Представления на основе классов

# Перечень встроенных CBV
# https://ccbv.co.uk/projects/Django/5.0/

# from django.shortcuts import render
# from django.http import HttpResponseRedirect

# Импорт базовых классов View, TemplateView и ListView
# from django.views import View
# from django.views.generic import TemplateView
from django.views.generic import ListView

from .models import Post


# Рассмотрим два варианта представлений,
# FBV (на основе функций) и CBV (на основе классов) для страницы,
# отображающей форму добавления публикации.

# FBV
# def post_form(request, pk):
#     template_name = 'post_form.html'
#     form = MyForm()

#     if request.method == 'POST':
#         form = MyForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('post_list/')
#     return render(request, template_name, {'form': form})

# CBV
# class PostView(View):
#     template_name = 'post_form.html'
#     form_class = MyForm

#     Для каждого типа запросов (GET, POST и т.д.) создается отдельный метод,
#     который вызывается при получении соответствующего типа запроса.
#     def get(self, request, *args, **kwargs):
#         form = self.form_class()
#         return render(request, self.template_name, {'form': form})

#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             form.save()
#             return HttpResponseRedirect('post_list/')
#         else:
#             return render(request, self.template_name, {'form': form})


# Создаем класс представления на основе встроенного класса TemplateView.
# По функционалу он ничем от обычного применения TemplateView не отличается.
# class ContactsView(TemplateView):
#     Передаем путь и название шаблона, который будет применяться,
#     встроенному свойству класса template_name.
#     template_name = 'posts/contacts.html'


# Рассмотрим кейс получения списка публикаций двумя способами,
# посредством FBV и CBV.

# FBV
# def post_list(request):
#     posts = Post.objects.all()
#     return render(request, 'post_list.html', {'post_list': posts})

# CBV
# Для этого создаем класс представления, дочерний встроенному классу ListView.
# class PostListView(ListView):
#     Для определения набора данных, которые будут переданы в качестве
#     контекста зададим значение встроенному свойству model.
#     model = Post


# Реализация представления для списка публикаций с настройкой параметров.
class PostList2View(ListView):
    # Если хотим получить не все объекты модели, а только часть,
    # определим значение встроенного свойства queryset (тип данных QuerySet).
    queryset = Post.objects.filter(title__endswith='2')

    # Для возможности переопределения имени переменной, в которой передается
    # шаблону набор объектов (вместо автоматически сформированного имени),
    # зададим встроенное свойство context_object_name.
    context_object_name = 'posts'

    # Для переопределения шаблона, использованного по умолчанию,
    # необходимо задать значение встроенному свойству template_name.
    template_name = 'posts/post_list_new.html'

lesson22/my_edu_project/templates/posts/contacts.html
<!-- Шаблон страницы, не использующий контекст,
    для представлений TemplateView и ContactsView -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Контакты</title>
</head>
<body>
    <h1>Наши контакты</h1>
    <div>
        <h2>Магомедов Магомед</h2>
        <p>Программист</p>
        <p>8 888 888 88 88</p>
    </div>
    <!-- Код для генерации ссылки на список публикаций -->
    <a href="{% url 'posts:post_list' %}">Список публикаций</a>
</body>
</html>

lesson22/my_edu_project/templates/posts/post_list.html
<!-- Шаблон списка публикаций для представления PostListView -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список публикаций</title>
</head>
<body>
<h1>Список публикаций</h1>
<ul>
    {% for post in post_list %}
        <li>
            <div>{{ post.title }}</div>
            <div>{{ post.text }}</div>
        </li>
    {% endfor %}
</ul>
</body>
</html>

lesson22/my_edu_project/templates/posts/post_list_new.html
<!-- Шаблон списка публикаций для представления PostList2View -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Список публикаций</title>
</head>
<body>
<h1>Список публикаций</h1>
<ul>
    {% for post in posts %}
        <li>
            <div>{{ post.title }}</div>
            <div>{{ post.text }}</div>
        </li>
    {% endfor %}
</ul>
</body>
</html>